services:
  # Servicio para la base de datos MySQL
  mysql:
    image: mysql:latest  
    container_name: mysql-db
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: productstech_db
    ports:
      - "3356:3356"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - productstech_network

  # Servicio para la API Backend
  backend:
    build:
      context: ./Backend  
      dockerfile: Dockerfile
    container_name: products_tech_backend
    ports:
      - 8009:8009
    environment:
      - DB_HOST=mysql
      - DB_USER=username
      - DB_PASSWORD=password
      - DB_NAME=productstech_db
    restart: always
    depends_on:
      - mysql
    networks:
      - productstech_network
      
  # Servicio para la base de datos MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - productstech_network

  # Servicio para Mongo Express (interfaz web para MongoDB)
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINPASSWORD: password  
      ME_CONFIG_MONGODB_SERVER_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: username
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - productstech_network

  apache:
    image: httpd:latest
    container_name: apache-server
    ports:
      - "2024:2024"
    volumes:
      - ./VentanaUno:/usr/local/apache2/htdocs/
    networks:
      - productstech_network

volumes:
  mongo_data:
  mysql_data:

networks:
  productstech_network:
    driver: bridge
