services:
  # Servicio para la base de datos MySQL
  mysql:
    image: mysql:latest  
    container_name: ag_products_tech_mysql-db
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: productstech_db
    ports:
      - "3302:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ag

  # Servicio para la API Backend
  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    container_name: ag_products_tech_backend
    ports:
      - 8009:8009
    environment:
      - DB_HOST=127.0.0.1
      - DB_USER=username
      - DB_PASSWORD=password
      - DB_NAME=productstech_db
      - DB_PORT=3302
    restart: always
    depends_on:
      - mysql
    networks:
      - ag

  apache:
    image: httpd:latest
    container_name: ag_products_tech_apache_server
    ports:
      - "2024:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
    networks:
      - ag

volumes:
  mysql_data:

networks:
  ag:
    external: true